export const DANH_SACH_NGAN_HANG: readonly string[] = [
  "Vietcombank",
  "VietinBank",
  "BIDV",
  "Agribank",
  "Techcombank",
  "MB Bank",
  "ACB",
  "VPBank",
  "TPBank",
  "Sacombank",
  "HDBank",
  "VIB",
  "SHB",
  "MSB",
  "OCB",
  "LienVietPostBank",
  "SeABank",
  "Eximbank",
  "Nam A Bank",
  "PVcomBank",
  "ABBANK",
  "Bac A Bank",
  "Kienlongbank",
  "NCB",
  "PGBank",
  "Saigonbank",
  "Viet Capital Bank",
  "Woori Bank",
  "Standard Chartered",
  "HSBC",
];
