# -*- coding: utf-8 -*-
"""Sinh docs/kich-ban-va-so-do-hoat-dong.md – 25 use case RedBus."""
from pathlib import Path

OUT = Path(__file__).resolve().parent / "kich-ban-va-so-do-hoat-dong.md"

# (uc_id, ten, actor_chinh, mo_ta, input, output, basic, alt, exc, activity)
UC = [
    ("UC01", "Đăng nhập / đăng xuất", "Quản trị viên, Nhân viên, Khách hàng, Khách vãng lai",
     "Người dùng xác thực tên đăng nhập và mật khẩu để truy cập chức năng theo vai trò; đăng xuất xóa phiên cục bộ.",
     "Tên đăng nhập, mật khẩu hợp lệ.",
     "JWT và thông tin người dùng; chuyển hướng theo vai trò (CUSTOMER → đặt vé; ADMIN/STAFF → quản trị).",
     "1. Actor mở form Đăng nhập — Bắt đầu\n2. Nhập tên đăng nhập, mật khẩu\n3. Gửi POST /xac-thuc/dang-nhap\n4. Hệ thống xác thực, trả JWT\n5. Lưu phiên, chuyển trang — Kết thúc",
     "1a. Đăng xuất: xóa token trong localStorage, về trang chủ — Kết thúc",
     "3a. Sai thông tin → báo lỗi đăng nhập\n3b. Tài khoản bị khóa (hoatDong=false) → từ chối đăng nhập",
     "● → Mở form → Nhập TK/MK → Xác thực? → [Đúng] Lưu JWT → Chuyển hướng → ◉ | [Sai] Báo lỗi → ◉"),
    ("UC02", "Đăng ký / quên mật khẩu", "Khách hàng, Khách vãng lai",
     "Khách vãng lai đăng ký tài khoản CUSTOMER hoặc đặt lại mật khẩu qua OTP email.",
     "Họ tên, tên đăng nhập, email, mật khẩu; hoặc email + OTP + mật khẩu mới.",
     "Tài khoản CUSTOMER mới (tự đăng nhập) hoặc mật khẩu được đặt lại.",
     "Đăng ký: 1. Chọn Đăng ký — Bắt đầu 2. Nhập hồ sơ 3. POST /xac-thuc/dang-ky 4. Tạo TaiKhoan+KhachHang 5. Trả JWT — Kết thúc",
     "Quên MK: 1. Nhập email → gửi OTP 2. Nhập OTP+mật khẩu mới → POST dat-lai — Kết thúc",
     "3a. Trùng tên đăng nhập/email 3b. Mật khẩu <6 ký tự 3c. OTP sai/hết hạn (10 phút)",
     "● → {Đăng ký|Quên MK} → Kiểm tra → [OK] Lưu/đổi MK → ◉"),
    ("UC03", "Xem tổng quan (Dashboard)", "Quản trị viên, Nhân viên",
     "Xem KPI vận hành: doanh thu, số vé, chuyến xe, đánh giá, khuyến mãi, tin tức.",
     "Đã đăng nhập ADMIN/STAFF.",
     "Bảng chỉ số tổng hợp; liên kết nhanh tới module quản trị.",
     "1. Vào /quan-tri/tong-quan — Bắt đầu 2. GET /bao-cao/mo-rong 3. Hiển thị KPI 4. (Tùy chọn) Cập nhật số liệu — Kết thúc",
     "4a. Nhấn liên kết nhanh → chuyển module tương ứng",
     "2a. Lỗi API → thông báo không tải được dữ liệu",
     "● → Tải KPI → Hiển thị dashboard → ◉"),
    ("UC04", "Quản lý tuyến đường", "Quản trị viên, Nhân viên",
     "Thêm, sửa tuyến (điểm đi/đến, km, thời gian); Quản trị viên được xóa.",
     "Điểm đi, điểm đến, khoảng cách km, thời gian ước tính (phút).",
     "Danh sách tuyến cập nhật; có thể cấu hình điểm dừng trên cùng trang.",
     "1. Chọn Tuyến đường — Bắt đầu 2. + Thêm/Sửa 3. Chọn địa danh, nhập km/phút 4. Lưu → POST/PUT /tuyen-duong — Kết thúc",
     "2a. Quản trị viên nhấn Xóa → DELETE (chỉ ADMIN)",
     "3a. Điểm đi=điểm đến 3b. km/phút ≤0 3c. Trùng cặp tuyến 4a. Hủy → dừng",
     "● → Chọn thao tác → Nhập tuyến → Kiểm tra → Lưu CSDL → ◉"),
    ("UC05", "Quản lý loại xe", "Quản trị viên, Nhân viên",
     "Quản lý loại xe (tên, mô tả, tiện ích, ảnh); ADMIN xóa loại xe.",
     "Tên loại xe (bắt buộc); ảnh jpg/png/webp/gif ≤8MB.",
     "Danh sách loại xe và ảnh minh họa.",
     "1. Mở Loại xe — Bắt đầu 2. Thêm/Sửa thông tin 3. Upload ảnh 4. Lưu — Kết thúc",
     "2a. ADMIN xóa loại xe 3a. Xóa ảnh (ADMIN/STAFF)",
     "2b. Trùng tên 3b. File ảnh không hợp lệ",
     "● → Form loại xe → Upload ảnh? → Lưu → ◉"),
    ("UC06", "Quản lý xe khách", "Quản trị viên, Nhân viên",
     "Gán xe vật lý với loại xe, biển số, hãng, số chỗ.",
     "Mã loại xe, biển số, số chỗ (>0).",
     "Danh sách xe khách.",
     "1. Mở Xe khách — Bắt đầu 2. Thêm/Sửa 3. Lưu POST/PUT /xe-khach — Kết thúc",
     "2a. ADMIN xóa xe",
     "3a. Trùng biển số 3b. Thiếu loại xe/số chỗ",
     "● → Nhập xe → Kiểm tra → Lưu → ◉"),
    ("UC07", "Quản lý ghế ngồi", "Quản trị viên, Nhân viên",
     "Xem sơ đồ ghế theo xe; chuyển ghế AVAILABLE ↔ BLOCKED.",
     "Chọn xe; trạng thái ghế hợp lệ.",
     "Sơ đồ ghế cập nhật.",
     "1. Chọn xe — Bắt đầu 2. GET /ghe-ngoi/xe/{ma} 3. Click ghế trống/khóa 4. PUT trang-thai — Kết thúc",
     "—",
     "3a. Ghế đang giữ/đã bán → không đổi được",
     "● → Chọn xe → Hiển thị sơ đồ → Đổi trạng thái? → Cập nhật → ◉"),
    ("UC08", "Quản lý điểm dừng chân", "Quản trị viên, Nhân viên",
     "Cấu hình điểm dừng theo tuyến: tên, thứ tự, thời gian dừng.",
     "Mã tuyến, tên điểm, thứ tự ≥0, phút dừng ≥0.",
     "Timeline điểm dừng trên tuyến.",
     "1. Chọn tuyến — Bắt đầu 2. Thêm/Sửa điểm dừng 3. Lưu — Kết thúc",
     "2a. ADMIN xóa điểm dừng",
     "3a. Trùng thứ tự/tên trên cùng tuyến",
     "● → Chọn tuyến → Nhập điểm dừng → Lưu → ◉"),
    ("UC09", "Quản lý chuyến xe, sinh lịch", "Quản trị viên, Nhân viên",
     "Tạo/sửa chuyến; ADMIN sinh lịch hàng loạt (tối đa 31 ngày).",
     "Tuyến, xe, giờ khởi hành, giá vé; gen: từ ngày, số ngày.",
     "Danh sách chuyến theo bộ lọc.",
     "1. Mở Chuyến xe — Bắt đầu 2. Thêm/Sửa chuyến 3. Lưu — Kết thúc",
     "2a. ADMIN: Gen lịch POST /chuyen-xe/gen-lich 2b. ADMIN xóa chuyến",
     "3a. Giá ≤0 3b. Giờ đến ≤ khởi hành 3c. Trùng tuyến+xe+giờ 3d. Gen >31 ngày",
     "● → {Thêm|Sửa|Gen lịch} → Kiểm tra → Lưu → ◉"),
    ("UC10", "Quản lý tài khoản khách hàng", "Quản trị viên, Nhân viên",
     "Thêm/sửa/khóa tài khoản CUSTOMER; tự liên kết TaiKhoan+KhachHang.",
     "Tên đăng nhập, email, mật khẩu, họ tên (thêm); hồ sơ+hoatDong (sửa).",
     "Danh sách khách với trạng thái Hoạt động/Đã khóa.",
     "1. Mở Khách hàng — Bắt đầu 2. + Thêm hoặc Sửa 3. Nhập thông tin 4. Lưu — Kết thúc",
     "2a. Bỏ chọn Tài khoản hoạt động → khóa đăng nhập",
     "4a. Trùng TK/email 4b. MK <6 ký tự 4c. Hủy",
     "● → Form KH → Kiểm tra → Tạo/cập nhật → ◉"),
    ("UC11", "Quản lý khuyến mãi", "Quản trị viên, Nhân viên",
     "Tạo mã giảm giá (%), thời hạn, giới hạn sử dụng.",
     "Mã, % giảm 1–100, ngày bắt đầu/kết thúc.",
     "Danh sách mã khuyến mãi.",
     "1. Mở Khuyến mãi — Bắt đầu 2. Thêm/Sửa 3. Lưu — Kết thúc",
     "2a. ADMIN xóa mã",
     "3a. Trùng mã 3b. Ngày kết thúc ≤ bắt đầu",
     "● → Nhập mã KM → Kiểm tra → Lưu → ◉"),
    ("UC12", "Quản lý tin tức", "Quản trị viên, Nhân viên",
     "Đăng/sửa bài tin (tiêu đề, nội dung HTML, ảnh, hiển thị).",
     "Tiêu đề, nội dung bài viết.",
     "Danh sách tin tức quản trị.",
     "1. Mở Tin tức (QT) — Bắt đầu 2. Thêm/Sửa 3. Upload ảnh (tùy chọn) 4. Lưu — Kết thúc",
     "2a. ADMIN xóa tin",
     "3a. Thiếu tiêu đề/nội dung",
     "● → Soạn tin → Upload ảnh? → Lưu → ◉"),
    ("UC13", "Quản lý hỏi đáp (FAQ)", "Quản trị viên, Nhân viên",
     "Xem câu hỏi khách gửi và trả lời; câu đã trả lời hiển thị công khai qua API.",
     "Nội dung trả lời.",
     "Trạng thái câu hỏi → DA_TRA_LOI.",
     "1. GET /hoi-dap/quan-tri/tat-ca — Bắt đầu 2. Chọn câu hỏi 3. Nhập trả lời 4. PUT /hoi-dap/{ma}/tra-loi — Kết thúc",
     "—",
     "3a. Nội dung trả lời trống\n*Ghi chú: chưa có giao diện quản trị; thao tác qua API.",
     "● → Danh sách Hỏi → Nhập trả lời → Lưu → ◉"),
    ("UC14", "Báo cáo thống kê, xuất CSV", "Quản trị viên, Nhân viên",
     "Xem biểu đồ doanh thu, vé, tuyến; xuất file CSV.",
     "Đã đăng nhập quản trị.",
     "Biểu đồ và file CSV tải về.",
     "1. Mở Báo cáo — Bắt đầu 2. Tải KPI+biểu đồ 3. Nhấn Xuất CSV — Kết thúc",
     "2a. Làm mới số liệu",
     "3a. Lỗi tải file",
     "● → Tải biểu đồ → Xuất CSV? → Tải file → ◉"),
    ("UC15", "Tìm kiếm chuyến xe", "Khách hàng, Khách vãng lai",
     "Tìm chuyến theo tuyến, ngày, bộ lọc giá/loại xe/giờ; xem ghế trống.",
     "Mã tuyến, thời điểm khởi hành; bộ lọc tùy chọn.",
     "Danh sách chuyến và sơ đồ ghế.",
     "1. Chọn tuyến+ngày — Bắt đầu 2. GET /chuyen-xe/tim-kiem 3. Hiển thị kết quả 4. Chọn chuyến → tải ghế — Kết thúc",
     "1a. Từ trang chủ → chuyển /dat-ve kèm query",
     "2a. Không có chuyến → thông báo trống",
     "● → Nhập điều kiện → Tìm kiếm → Có chuyến? → Hiển thị → ◉"),
    ("UC16", "Đặt vé, chọn ghế", "Khách hàng",
     "Chọn 1–10 ghế, điểm lên/xuống; giữ vé PENDING 15 phút.",
     "Mã chuyến, danh sách ghế; điểm dừng (tùy chọn).",
     "Vé PENDING, mã vé hiển thị; email+thông báo.",
     "1. Chọn ghế (1–10) — Bắt đầu 2. Xác nhận đặt 3. POST /ve-xe/dat 4. Tạo vé PENDING — Kết thúc",
     "1a. Chưa đăng nhập → mở form đăng ký/đăng nhập",
     "2a. Ghế đã giữ/khóa 2b. >10 ghế 2c. Điểm lên/xuống sai tuyến",
     "● → Chọn ghế → Đăng nhập? → Đặt vé → Giữ 15p → ◉"),
    ("UC17", "Thanh toán (PayOS / tiền mặt)", "Khách hàng",
     "Thanh toán vé PENDING bằng tiền mặt hoặc PayOS; áp mã khuyến mãi.",
     "Mã vé PENDING; mã KM (tùy chọn).",
     "Vé PAID; giao dịch và email xác nhận.",
     "Tiền mặt: POST /thanh-toan/ve/{ma}/tien-mat — Kết thúc | PayOS: tạo link → thanh toán → webhook/kiểm tra kết quả",
     "1a. Nhập mã khuyến mãi trước khi thanh toán",
     "2a. Vé hết hạn/không phải của mình 2b. Mã KM không hợp lệ 2c. PayOS chưa cấu hình",
     "● → Chọn PTTT → {Tiền mặt|PayOS} → Xác nhận → Vé PAID → ◉"),
    ("UC18", "Tra cứu vé, vé điện tử (QR)", "Khách hàng, Khách vãng lai",
     "Tra cứu công khai bằng mã vé+SĐT; khách đăng nhập xem vé điện tử PAID.",
     "Mã vé hiển thị + số điện thoại; hoặc JWT (vé của tôi).",
     "Thông tin vé; mã QR tra cứu.",
     "Công khai: GET /ve-xe/tra-cuu — Kết thúc | Đăng nhập: GET /ve-xe/{ma}/dien-tu",
     "1a. Quét QR điền sẵn mã vé",
     "2a. Không tìm thấy 2b. SĐT không khớp 2c. Vé chưa PAID (vé điện tử)",
     "● → Nhập mã+SĐT → Tra cứu → Hiển thị/QR → ◉"),
    ("UC19", "Đổi ghế / đổi chuyến / hủy vé", "Khách hàng",
     "Hủy vé PENDING; API đổi ghế/chuyến cho vé PENDING/PAID (trước giờ đi ≥2h).",
     "Mã vé; ghế/chuyến mới (đổi).",
     "Vé CANCELLED hoặc cập nhật ghế/chuyến.",
     "Hủy (UI): POST /ve-xe/{ma}/huy — Kết thúc",
     "Đổi ghế: POST /ve-xe/{ma}/doi-ghe | Đổi chuyến: POST /ve-xe/{ma}/doi-chuyen\n*Ghi chú: đổi ghế/chuyến có API, chưa có giao diện khách.",
     "2a. Vé PAID → không hủy online 2b. <2h trước giờ đi → không đổi 2c. Ghế mới đã có người",
     "● → Chọn vé → {Hủy|Đổi}? → Kiểm tra → Cập nhật → ◉"),
    ("UC20", "Quản lý hồ sơ, lịch sử thanh toán", "Khách hàng",
     "Xem/sửa hồ sơ; đổi mật khẩu; xem lịch sử giao dịch.",
     "Họ tên, SĐT, địa chỉ, email; mật khẩu cũ/mới.",
     "Hồ sơ cập nhật; bảng lịch sử thanh toán.",
     "Hồ sơ: GET/PUT /ho-so/cua-toi — Kết thúc | Lịch sử: GET /thanh-toan/lich-su",
     "1a. Đổi mật khẩu PUT /ho-so/mat-khau",
     "2a. Mật khẩu cũ sai 2b. Mật khẩu mới <6 ký tự",
     "● → Xem hồ sơ → Sửa/Lịch sử? → Lưu → ◉"),
    ("UC21", "Đánh giá chuyến đi", "Khách hàng",
     "Đánh giá 1–5 sao chuyến đã đi, vé PAID, chưa đánh giá.",
     "Mã chuyến, điểm (1–5), nhận xét.",
     "Đánh giá lưu CSDL; hiển thị công khai.",
     "1. GET /danh-gia/ve-cho-danh-gia — Bắt đầu 2. Chọn chuyến 3. POST /danh-gia — Kết thúc",
     "—",
     "3a. Đã đánh giá chuyến này 3b. Chuyến chưa khởi hành",
     "● → Danh sách chuyến → Chấm điểm → Gửi → ◉"),
    ("UC22", "Xử lý hỗ trợ / trả lời chat", "Quản trị viên, Nhân viên",
     "Nhân viên/Quản trị mở /quan-tri/ho-tro, chọn khách hàng, đọc và trả lời tin nhắn qua API chat.",
     "Khách được chọn (maTaiKhoan), nội dung tin nhắn.",
     "Tin nhắn lưu CSDL; hội thoại cập nhật (làm mới mỗi 5 giây).",
     "1. Chọn Hỗ trợ / Chat — Bắt đầu\n2. Tải danh sách khách GET /khach-hang\n"
     "3. Chọn khách → GET /chat/hoi-thoai?doiPhuong=\n4. Nhập và POST /chat/gui — Kết thúc",
     "3a. Tìm khách theo tên/SĐT/tài khoản",
     "4a. Nội dung trống 4b. Đối phương không hợp lệ",
     "● → Chọn khách → Tải hội thoại → Gửi trả lời → ◉"),
    ("UC23", "Nhận thông báo thời gian thực (SSE)", "Quản trị viên, Nhân viên, Khách hàng",
     "Nhận thông báo qua Server-Sent Events khi có sự kiện (đặt vé, thanh toán…).",
     "JWT hợp lệ.",
     "Toast thông báo; danh sách trong /thong-bao.",
     "1. Đăng nhập — Bắt đầu 2. Mở SSE /thong-bao/stream 3. Nhận sự kiện 4. Đánh dấu đã đọc — Kết thúc",
     "4a. Xem danh sách GET /thong-bao",
     "2a. Mất kết nối SSE → ngắt kết nối",
     "● → Kết nối SSE → Nhận TB → Hiển thị → ◉"),
    ("UC24", "Gửi / nhận tin nhắn hỗ trợ (chat)", "Quản trị viên, Nhân viên, Khách hàng",
     "Trao đổi tin nhắn 1-1: khách tại /ho-tro; quản trị tại /quan-tri/ho-tro.",
     "Mã người nhận, nội dung tin.",
     "Lịch sử hội thoại hiển thị trong khung chat.",
     "1. Mở trang Hỗ trợ — Bắt đầu\n2. GET /chat/ho-tro (khách) hoặc chọn khách (QT)\n"
     "3. GET /chat/hoi-thoai 4. POST /chat/gui — Kết thúc",
     "2a. Khách chọn nhân viên hỗ trợ (nếu nhiều STAFF/ADMIN)",
     "4a. Nội dung trống 4b. Gửi cho chính mình 4c. Người nhận không tồn tại",
     "● → Mở chat → Tải hội thoại → Gửi/nhận → ◉"),
    ("UC25", "Xem tin tức, FAQ, đánh giá công khai", "Tất cả actor (kể cả Khách vãng lai)",
     "Đọc tin tức, FAQ (trang chủ tĩnh + API động), đánh giá công khai.",
     "Không cần đăng nhập.",
     "Danh sách tin, chi tiết bài, đánh giá mẫu.",
     "1. GET /tin-tuc — Bắt đầu 2. Xem chi tiết /tin-tuc/{ma} 3. Xem đánh giá /danh-gia/cong-khai — Kết thúc",
     "1a. FAQ trên trang chủ (nội dung tĩnh)",
     "2a. Tin không tồn tại/không hiển thị",
     "● → Duyệt tin/FAQ/ĐG → Hiển thị → ◉"),
]

SECTIONS = [
    ("2.2.3.1", "Actor Quản trị viên",
     "Quản trị viên (ADMIN) có toàn quyền vận hành: cấu hình danh mục, sinh lịch chuyến, xóa dữ liệu, quản lý khách hàng và xem báo cáo.",
     ["UC01", "UC03", "UC04", "UC05", "UC06", "UC07", "UC08", "UC09", "UC10",
      "UC11", "UC12", "UC13", "UC14", "UC22", "UC23", "UC24", "UC25"]),
    ("2.2.3.2", "Actor Nhân viên",
     "Nhân viên (STAFF) thực hiện vận hành hàng ngày tương tự Quản trị viên nhưng không xóa danh mục và không sinh lịch chuyến hàng loạt.",
     ["UC01", "UC03", "UC04", "UC05", "UC06", "UC07", "UC08", "UC09", "UC10",
      "UC11", "UC12", "UC13", "UC14", "UC22", "UC23", "UC24", "UC25"]),
    ("2.2.3.3", "Actor Khách hàng",
     "Khách hàng (CUSTOMER) đăng ký/đăng nhập để đặt vé, thanh toán, quản lý vé cá nhân và tương tác hỗ trợ.",
     ["UC01", "UC02", "UC15", "UC16", "UC17", "UC18", "UC19", "UC20", "UC21", "UC23", "UC24", "UC25"]),
    ("2.2.3.4", "Actor Khách vãng lai",
     "Khách vãng lai truy cập không đăng nhập: tìm chuyến, tra cứu vé, xem tin tức/FAQ/đánh giá; có thể đăng ký hoặc đăng nhập.",
     ["UC01", "UC02", "UC15", "UC18", "UC25"]),
]

UC_MAP = {u[0]: u for u in UC}


def row(label, val):
    v = val.replace("\n", "<br>")
    return f"| **{label}** | {v} |"


def render_uc(uc_id, sec_idx, uc_idx, bang_start=22):
    u = UC_MAP[uc_id]
    bang = bang_start + list(UC_MAP.keys()).index(uc_id)
    hinh = 16 + list(UC_MAP.keys()).index(uc_id)
    lines = [
        f"#### {sec_idx}.{uc_idx}. {uc_id} – {u[1]}",
        "",
        f"**Bảng 2.{bang} – Đặc tả use case {uc_id}: {u[1]}**",
        "",
        "| Hạng mục | Nội dung |",
        "|----------|----------|",
        row("Use case name", u[1]),
        row("Description", u[3]),
        row("Actors", u[2]),
        row("Input", u[4]),
        row("Output", u[5]),
        row("Basic flow", u[6]),
        row("Alternative flow", u[7]),
        row("Exception flow", u[8]),
        "",
        f"**Hình 2.{hinh} – Activity Diagram: {uc_id} – {u[1]}**",
        "",
        f"Luồng hoạt động: `{u[9]}`",
        "",
    ]
    return "\n".join(lines)


def main():
    lines = [
        "# 2.2.3. Kịch bản và sơ đồ hoạt động",
        "",
        "Mỗi use case được mô tả bằng **bảng đặc tả** (tên, mô tả, actor, input/output, "
        "luồng cơ bản, luồng thay thế, luồng ngoại lệ) và **sơ đồ hoạt động** (ký hiệu: "
        "● bắt đầu, ◉ kết thúc, hình thoi = điều kiện). Nội dung bám theo triển khai "
        "thực tế của hệ thống RedBus.",
        "",
        "**Ma trận Use case – Actor:** xem Bảng 2.21 (mục 2.2.1).",
        "",
        "---",
        "",
    ]

    for sec_id, sec_title, sec_desc, uc_list in SECTIONS:
        lines += [f"## {sec_id}. {sec_title}", "", sec_desc, ""]
        if sec_id == "2.2.3.2":
            lines += [
                "> **Phân quyền so với Quản trị viên:** Nhân viên không thấy nút **Xóa** "
                "trên Tuyến, Xe, Loại xe, Điểm dừng, Chuyến xe, Khuyến mãi, Tin tức; "
                "không dùng **Gen lịch** chuyến xe. Các kịch bản dưới đây giống Quản trị "
                "viên, trừ các bước 2a (xóa/gen) trong Alternative flow.",
                "",
            ]
        for i, uc_id in enumerate(uc_list, 1):
            lines.append(render_uc(uc_id, sec_id, i))
        lines += ["---", ""]

    lines += [
        "## Phụ lục – Bảng tra cứu nhanh 25 Use case",
        "",
        "| Mã | Tên | Actor chính | Route / API chính |",
        "|:---:|-----|-------------|-------------------|",
    ]
    routes = {
        "UC01": "/dang-nhap · POST /xac-thuc/dang-nhap",
        "UC02": "/dang-ky · POST /xac-thuc/dang-ky, /quen-mat-khau/*",
        "UC03": "/quan-tri/tong-quan · GET /bao-cao/mo-rong",
        "UC04": "/quan-tri/tuyen-duong · /tuyen-duong",
        "UC05": "/quan-tri/loai-xe · /loai-xe",
        "UC06": "/quan-tri/xe-khach · /xe-khach",
        "UC07": "/quan-tri/ghe-ngoi · /ghe-ngoi",
        "UC08": "/quan-tri/diem-dung · /diem-dung",
        "UC09": "/quan-tri/chuyen-xe · /chuyen-xe",
        "UC10": "/quan-tri/khach-hang · /khach-hang",
        "UC11": "/quan-tri/khuyen-mai · /khuyen-mai",
        "UC12": "/quan-tri/tin-tuc · /tin-tuc",
        "UC13": "API · /hoi-dap/quan-tri/*",
        "UC14": "/quan-tri/bao-cao · /bao-cao/*",
        "UC15": "/dat-ve · GET /chuyen-xe/tim-kiem",
        "UC16": "/dat-ve · POST /ve-xe/dat",
        "UC17": "/ve-cua-toi · /thanh-toan/*",
        "UC18": "/tra-cuu-ve · GET /ve-xe/tra-cuu",
        "UC19": "/ve-cua-toi · POST /ve-xe/{ma}/huy",
        "UC20": "/ho-so · /lich-su-thanh-toan",
        "UC21": "/danh-gia · POST /danh-gia",
        "UC22": "/quan-tri/ho-tro · /chat/*",
        "UC23": "/thong-bao · GET /thong-bao/stream",
        "UC24": "/ho-tro · /quan-tri/ho-tro · /chat/*",
        "UC25": "/tin-tuc · GET /tin-tuc, /danh-gia/cong-khai",
    }
    for u in UC:
        lines.append(f"| {u[0]} | {u[1]} | {u[2]} | {routes[u[0]]} |")

    lines += [
        "",
        "---",
        "",
        "*Tài liệu sinh tự động: `python docs/gen_kich_ban_uc.py`*",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(UC)} use cases)")


if __name__ == "__main__":
    main()
